### ISSUE TITLE
Production example requests contain references to staging site

### ISSUE THREAD

**Issue by tnation14** [azavea/raster-foundry-docs#19]
In the sample `cURL` requests on the https://docs.rasterfoundry.com, the target URL is `https://app.staging.rasterfoundry.com` instead of `https://app.rasterfoundry.com`.
<img width="728" alt="screen shot 2017-05-22 at 9 53 09 am" src="https://cloud.githubusercontent.com/assets/2507188/26312317/2c0a1332-3ed5-11e7-999c-3e432fc31170.png">

**Comment by Lknechtli** [comment]
Closed by #23
