### ISSUE TITLE
Incomplete Exports section

### ISSUE THREAD

**Issue by tnation14** [azavea/raster-foundry-docs#21]
The `Exports` section of the Production page is missing some content that appears in staging. The `Get Export Details` section looks like this:
![image](https://cloud.githubusercontent.com/assets/2507188/26315496/5593d3dc-3edf-11e7-8dae-0a74ca6e25b2.png)

And there is no content for any of the following sections:

- Update an export
- Delete an export
- Get export details

Blocking azavea/raster-foundry#1617

**Comment by Lknechtli** [comment]
Turns out this is because we aren't handling nested `allOf` definitions very well. There was exported by an update which nested `BaseCreate` inside of `ExportCreate` inside of `Export`.
